# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='optout',
            field=models.BooleanField(default=False),
        ),
    ]
