# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='horse_image',
            field=models.ImageField(upload_to='media/reviews'),
        ),
    ]
